const data = {
    products:[
        
          {
            name: 'Lipstick',
            slug: 'Lipstick',
            category: 'Fashion',
            image: '/images/lip.jpg',
            price: 2500,
            brand: 'Lakme',
            rating: 3.2,
            numReviews: 10,
            countInStock: 20,
            description:'Red shade Lipstick',
          },
          {
            name: 'Handbag',
            slug: 'Handbag for women',
            category: 'Fashion',
            image: '/images/bag.jpg',
            price: 4000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Handbags for women',
          },
          {
            name: 'Heels',
            slug: 'Heels for women',
            category: 'Fashion',
            image: '/images/heels2.jpg',
            price: 4000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Heels',
          },
          {
            name: 'Heels',
            slug: 'Green Heels for women',
            category: 'Fashion',
            image: '/images/green.jpg',
            price: 2000,
            brand: 'Nike',
            rating: 4.8,
            numReviews: 9,
            countInStock: 20,
            description: 'Heels Green',
          },
          {
            name: 'Watch',
            slug: 'watch for women',
            category: 'Watches',
            image: '/images/image1.png',
            price: 3500,
            brand: 'Daniel Willington',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Watch with bracelet',
          },
        
         
          {
            name: 'Watch',
            slug: 'watch for men',
            category: 'Watches',
            image: '/images/watch3.png',
            price: 3000,
            brand: 'Daniel Willington',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Mens watch',
          },
        ],
      };
      
      export default data;
  